core: initramfs-framework: add custom script changes, add factory reset script
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>

diff --git a/recipes-core/initrdscripts/initramfs-framework/rorootfs-overlay b/recipes-core/initrdscripts/initramfs-framework/rorootfs-overlay
--- a/recipes-core/initrdscripts/initramfs-framework/rorootfs-overlay
+++ b/recipes-core/initrdscripts/initramfs-framework/rorootfs-overlay
@@ -85,9 +85,14 @@ rorootfs_run() {
 	ROOT_MOUNT=$ROOTFS_DIR
 	ROOT_RODEVICE=""
 	ROOT_RWDEVICE=""
+	ROOT_RWDEVICE2=""
 	ROOT_ROMOUNT="/media/rfs/ro"
 	ROOT_RWMOUNT="/media/rfs/rw"
+	ROOT_RWMOUNT2="/media/rfs/rw2"
 	ROOT_RWRESET="no"
+	ROOT_RWRESET2="no"
+	FACTORY_RESET="no"
+	FACTORY_RESET_CMD="/usr/sbin/factory-reset"
 
 	ROOT_ROFSTYPE=""
 	ROOT_ROMOUNTOPTIONS="noatime,nodiratime"
@@ -95,13 +100,19 @@ rorootfs_run() {
 	ROOT_RWFSTYPE=""
 	ROOT_RWMOUNTOPTIONS="rw,noatime,mode=755"
 
+	# By default, only one level of overlay is used
+	USE_RWOVERLAY2="no"
+
 	# the default values can be overriden by the kernel params
 	[ -n "$bootparam_init" ] && INIT="$bootparam_init"
 	[ -n "$bootparam_rootinit" ] && ROOT_ROINIT="$bootparam_rootinit"
 	[ -n "$bootparam_rootrwreset" ] && ROOT_RWRESET="$bootparam_rootrwreset"
+	[ -n "$bootparam_rootrwreset2" ] && ROOT_RWRESET2="$bootparam_rootrwreset2"
+	[ -n "$bootparam_factoryreset" ] && FACTORY_RESET="$bootparam_factoryreset"
 
 	[ -n "$bootparam_root" ] && ROOT_RODEVICE="$(rorootfs_find_device "$bootparam_root")"
 	[ -n "$bootparam_rootrw" ] && ROOT_RWDEVICE="$(rorootfs_find_device "$bootparam_rootrw")"
+	[ -n "$bootparam_rootrw2" ] && ROOT_RWDEVICE2="$(rorootfs_find_device "$bootparam_rootrw2")"
 
 	[ -n "$bootparam_rootfstype" ] && ROOT_ROFSTYPE="$bootparam_rootfstype"
 	[ -n "$bootparam_rootoptions" ] && ROOT_ROMOUNTOPTIONS="$bootparam_rootoptions"
@@ -109,12 +120,30 @@ rorootfs_run() {
 	[ -n "$bootparam_rootrwfstype" ] && ROOT_RWFSTYPE="$bootparam_rootrwfstype"
 	[ -n "$bootparam_rootrwoptions" ] && ROOT_RWMOUNTOPTIONS="$bootparam_rootrwoptions"
 
+	[ -n "$bootparam_rootrwfstype2" ] && ROOT_RWFSTYPE2="$bootparam_rootrwfstype2"
+	[ -n "$bootparam_rootrwoptions2" ] && ROOT_RWMOUNTOPTIONS2="$bootparam_rootrwoptions2"
+
+	# We use 2nd level of overlay if rootrw2 was given in the kernel cmdline
+	# AND rwoverlaylvl was set to 2
+	if [ 2 -eq $bootparam_rwoverlaylvl ]; then
+		if [ -n "$bootparam_rootrw2" ]; then
+			USE_RWOVERLAY2="yes"
+		fi
+	fi
+
 	mkdir -p "$ROOT_MOUNT" "$ROOT_ROMOUNT" "$ROOT_RWMOUNT"
+	if [ "yes" = "$USE_RWOVERLAY2" ]; then
+		mkdir -p "$ROOT_RWMOUNT2"
+	fi
 
 	# run fsck on ROOT_RODEVICE
 	e2fsck -p "$ROOT_RODEVICE" > /dev/null 2>&1
 	# run fsck on ROOT_RWDEVICE
 	e2fsck -p "$ROOT_RWDEVICE" > /dev/null 2>&1
+	# run fsck on ROOT_RWDEVICE2 if in use
+	if [ "yes" = "$USE_RWOVERLAY2" ]; then
+		e2fsck -p "$ROOT_RWDEVICE2" > /dev/null 2>&1
+	fi
 
 	# Build mount options for read only root file system.
 	if [ -n "$ROOT_RODEVICE" ]; then
@@ -157,6 +186,14 @@ rorootfs_run() {
 		ROOT_RWDEVICE="tmpfs"
 	fi
 
+	# set mount params for 2nd level of overlay
+	if [ "yes" = "$USE_RWOVERLAY2" ]; then
+		ROOT_RWMOUNTPARAMS2="-o $ROOT_RWMOUNTOPTIONS2"
+		if [ -n "$ROOT_RWFSTYPE2" ]; then
+			ROOT_RWMOUNTPARAMS2="-t $ROOT_RWFSTYPE2 $ROOT_RWMOUNTPARAMS2"
+		fi
+	fi
+
 	# Mount read-write file system into initram root file system
 	if ! mount $ROOT_RWMOUNTPARAMS "$ROOT_RWDEVICE" "$ROOT_RWMOUNT" ; then
 		# if it fails for some reason, try to recover with forcing fsck
@@ -172,6 +209,23 @@ rorootfs_run() {
 		fi
 	fi
 
+	if [ "yes" = "$USE_RWOVERLAY2" ]; then
+		# Mount 2nd level read-write file system into initram root file system
+		if ! mount $ROOT_RWMOUNTPARAMS2 "$ROOT_RWDEVICE2" "$ROOT_RWMOUNT2" ; then
+			# if it fails for some reason, try to recover with forcing fsck
+			e2fsck -fp "$ROOT_RWDEVICE2" > /dev/null 2>&1
+			if ! mount $ROOT_RWMOUNTPARAMS2 "$ROOT_RWDEVICE2" "$ROOT_RWMOUNT2" ; then
+				# if it fails again, try to recover by creating a new
+				# filesystem
+				yes | mkfs.ext4 -L "rwoverlay" "$ROOT_RWDEVICE2"
+				if ! mount $ROOT_RWMOUNTPARAMS2 "$ROOT_RWDEVICE2" "$ROOT_RWMOUNT2" ; then
+					# if it still fails, give up
+					fatal "Could not mount read-write rootfs"
+				fi
+			fi
+		fi
+	fi
+
 	# Reset read-write file system if specified
 	if [ "yes" = "$ROOT_RWRESET" ] && [ -n "$ROOT_RWMOUNT" ]; then
 		if [ -n "$ROOT_RWMOUNT" ]; then
@@ -180,6 +234,22 @@ rorootfs_run() {
 		else
 			fatal "ROOT_RWMOUNT was not set!"
 		fi
+	fi
+
+	# Reset 2nd level read-write file system if specified
+	if [ "yes" = "$ROOT_RWRESET2" ] && [ -n "$ROOT_RWMOUNT2" ]; then
+		if [ -n "$ROOT_RWMOUNT2" ]; then
+			msg "rootrwreset2 was set to yes, resetting the 2nd level overlay partition..."
+			rm -rf ${ROOT_RWMOUNT2}/*
+		else
+			fatal "ROOT_RWMOUNT2 was not set!"
+		fi
+	fi
+
+	# Project-specific factory reset action
+	if [ "yes" = "$FACTORY_RESET" ]; then
+		msg "factoryreset was set to yes, performing factory reset..."
+		${FACTORY_RESET_CMD}
 	fi
 
 	# Determine which unification file system to use
@@ -197,31 +267,52 @@ rorootfs_run() {
 		"overlay")
 			msg "Mounting rw filesystem using overlay..."
 			mkdir -p $ROOT_RWMOUNT/upperdir $ROOT_RWMOUNT/work
-			mount -t overlay overlay \
-				-o "$(printf "%s%s%s" \
-					"lowerdir=$ROOT_ROMOUNT," \
-					"upperdir=$ROOT_RWMOUNT/upperdir," \
-					"workdir=$ROOT_RWMOUNT/work")" \
-				"$ROOT_MOUNT"
+			if [ "yes" = "$USE_RWOVERLAY2" ]; then
+				msg "Mounting 2nd level rw filesystem using overlay..."
+				mkdir -p $ROOT_RWMOUNT2/upperdir $ROOT_RWMOUNT2/work
+				mount -t overlay overlay \
+					-o "$(printf "%s%s%s" \
+						"lowerdir=$ROOT_RWMOUNT/upperdir:$ROOT_ROMOUNT," \
+						"upperdir=$ROOT_RWMOUNT2/upperdir," \
+						"workdir=$ROOT_RWMOUNT2/work")" \
+					"$ROOT_MOUNT"
+				mount -o remount,ro "$ROOT_RWMOUNT"
+			else
+				mount -t overlay overlay \
+					-o "$(printf "%s%s%s" \
+						"lowerdir=$ROOT_ROMOUNT," \
+						"upperdir=$ROOT_RWMOUNT/upperdir," \
+						"workdir=$ROOT_RWMOUNT/work")" \
+					"$ROOT_MOUNT"
+			fi
 			;;
 		"aufs")
 			msg "Mounting rw filesystem using aufs..."
 			mount -t aufs i\
 				-o "dirs=$ROOT_RWMOUNT=rw:$ROOT_ROMOUNT=ro" \
 				aufs "$ROOT_MOUNT"
+
+			if [ "yes" = "$USE_RWOVERLAY2" ]; then
+				msg "2nd level rw filesystem for aufs is not yet supported"
+			fi
 			;;
 		"")
 			fatal "No overlay filesystem type available"
 			;;
 	esac
 
-	# Move read-only and read-write root file system into the overlay
+	# Move read-only and read-write root file system(s) into the overlay
 	# file system
 	mkdir -p "$ROOT_MOUNT/$ROOT_ROMOUNT" "$ROOT_MOUNT/$ROOT_RWMOUNT"
 	mount -n --move "$ROOT_ROMOUNT" "$ROOT_MOUNT/$ROOT_ROMOUNT"
 	mount -n --move "$ROOT_RWMOUNT" "$ROOT_MOUNT/$ROOT_RWMOUNT"
 
+	if [ "yes" = "$USE_RWOVERLAY2" ]; then
+		mkdir -p "$ROOT_MOUNT/$ROOT_RWMOUNT2"
+		mount -n --move "$ROOT_RWMOUNT2" "$ROOT_MOUNT/$ROOT_RWMOUNT2"
+	fi
+
 	# switch to the actual init in the overlay root file system
 	exec switch_root "$ROOT_MOUNT" "$INIT" ||
-		fatal "Failed to switch_root!"
+		fatal "Failed to switch_root to $ROOT_MOUNT!"
 }
